[package]
name = "insulink"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
clap = { version = "4.5.9", features = ["derive", "env"] }
dotenv = "0.15.0"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.38.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
